--
-- PostgreSQL database dump
--

\restrict sTJl3Hi6DfgY8INlCdo82iGTgCljCpD5jTwFbjGkOHY4iWyKgeOE2FidZkxBi3f

-- Dumped from database version 15.19 (Debian 15.19-1.pgdg13+2)
-- Dumped by pg_dump version 15.19 (Debian 15.19-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_emailaddress; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.account_emailaddress (
    id integer NOT NULL,
    email character varying(254) NOT NULL,
    verified boolean NOT NULL,
    "primary" boolean NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.account_emailaddress OWNER TO postgresuser;

--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE; Schema: public; Owner: postgresuser
--

ALTER TABLE public.account_emailaddress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailaddress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_emailconfirmation; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.account_emailconfirmation (
    id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    sent timestamp with time zone,
    key character varying(64) NOT NULL,
    email_address_id integer NOT NULL
);


ALTER TABLE public.account_emailconfirmation OWNER TO postgresuser;

--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgresuser
--

ALTER TABLE public.account_emailconfirmation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailconfirmation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgresuser;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgresuser
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgresuser;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgresuser
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgresuser;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgresuser
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO postgresuser;

--
-- Name: chat_conversation; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.chat_conversation (
    id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    modified_at timestamp with time zone NOT NULL
);


ALTER TABLE public.chat_conversation OWNER TO postgresuser;

--
-- Name: chat_conversation_users; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.chat_conversation_users (
    id bigint NOT NULL,
    conversation_id uuid NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.chat_conversation_users OWNER TO postgresuser;

--
-- Name: chat_conversation_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgresuser
--

ALTER TABLE public.chat_conversation_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_conversation_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_conversationmessage; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.chat_conversationmessage (
    id uuid NOT NULL,
    body text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    conversation_id uuid NOT NULL,
    created_by_id uuid NOT NULL,
    sent_to_id uuid NOT NULL
);


ALTER TABLE public.chat_conversationmessage OWNER TO postgresuser;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgresuser;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgresuser
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgresuser;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgresuser
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgresuser;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgresuser
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgresuser;

--
-- Name: property_property; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.property_property (
    id uuid NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    price_per_night integer NOT NULL,
    bedrooms integer NOT NULL,
    bathrooms integer NOT NULL,
    guests integer NOT NULL,
    country character varying(255) NOT NULL,
    country_code character varying(10) NOT NULL,
    category character varying(255) NOT NULL,
    image character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    landlord_id uuid NOT NULL
);


ALTER TABLE public.property_property OWNER TO postgresuser;

--
-- Name: property_property_favorited; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.property_property_favorited (
    id bigint NOT NULL,
    property_id uuid NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.property_property_favorited OWNER TO postgresuser;

--
-- Name: property_property_favorited_id_seq; Type: SEQUENCE; Schema: public; Owner: postgresuser
--

ALTER TABLE public.property_property_favorited ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.property_property_favorited_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: property_reservation; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.property_reservation (
    id uuid NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    number_of_nights integer NOT NULL,
    guests integer NOT NULL,
    total_price double precision NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by_id uuid NOT NULL,
    property_id uuid NOT NULL
);


ALTER TABLE public.property_reservation OWNER TO postgresuser;

--
-- Name: socialaccount_socialaccount; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.socialaccount_socialaccount (
    id integer NOT NULL,
    provider character varying(200) NOT NULL,
    uid character varying(191) NOT NULL,
    last_login timestamp with time zone NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    extra_data jsonb NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.socialaccount_socialaccount OWNER TO postgresuser;

--
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE; Schema: public; Owner: postgresuser
--

ALTER TABLE public.socialaccount_socialaccount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialaccount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: socialaccount_socialapp; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.socialaccount_socialapp (
    id integer NOT NULL,
    provider character varying(30) NOT NULL,
    name character varying(40) NOT NULL,
    client_id character varying(191) NOT NULL,
    secret character varying(191) NOT NULL,
    key character varying(191) NOT NULL,
    provider_id character varying(200) NOT NULL,
    settings jsonb NOT NULL
);


ALTER TABLE public.socialaccount_socialapp OWNER TO postgresuser;

--
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE; Schema: public; Owner: postgresuser
--

ALTER TABLE public.socialaccount_socialapp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialapp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: socialaccount_socialtoken; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.socialaccount_socialtoken (
    id integer NOT NULL,
    token text NOT NULL,
    token_secret text NOT NULL,
    expires_at timestamp with time zone,
    account_id integer NOT NULL,
    app_id integer
);


ALTER TABLE public.socialaccount_socialtoken OWNER TO postgresuser;

--
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgresuser
--

ALTER TABLE public.socialaccount_socialtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: useraccount_user; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.useraccount_user (
    password character varying(128) NOT NULL,
    id uuid NOT NULL,
    email character varying(254) NOT NULL,
    name character varying(255),
    avatar character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    is_superuser boolean NOT NULL,
    is_staff boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    last_login timestamp with time zone
);


ALTER TABLE public.useraccount_user OWNER TO postgresuser;

--
-- Name: useraccount_user_groups; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.useraccount_user_groups (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.useraccount_user_groups OWNER TO postgresuser;

--
-- Name: useraccount_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgresuser
--

ALTER TABLE public.useraccount_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.useraccount_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: useraccount_user_user_permissions; Type: TABLE; Schema: public; Owner: postgresuser
--

CREATE TABLE public.useraccount_user_user_permissions (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.useraccount_user_user_permissions OWNER TO postgresuser;

--
-- Name: useraccount_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgresuser
--

ALTER TABLE public.useraccount_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.useraccount_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: account_emailaddress; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.account_emailaddress (id, email, verified, "primary", user_id) FROM stdin;
2	ishefat@outlook.com	f	t	ffe24a94-1408-4072-9bc9-c41186ada984
\.


--
-- Data for Name: account_emailconfirmation; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.account_emailconfirmation (id, created, sent, key, email_address_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add Token	7	add_token
26	Can change Token	7	change_token
27	Can delete Token	7	delete_token
28	Can view Token	7	view_token
29	Can add Token	8	add_tokenproxy
30	Can change Token	8	change_tokenproxy
31	Can delete Token	8	delete_tokenproxy
32	Can view Token	8	view_tokenproxy
33	Can add email address	9	add_emailaddress
34	Can change email address	9	change_emailaddress
35	Can delete email address	9	delete_emailaddress
36	Can view email address	9	view_emailaddress
37	Can add email confirmation	10	add_emailconfirmation
38	Can change email confirmation	10	change_emailconfirmation
39	Can delete email confirmation	10	delete_emailconfirmation
40	Can view email confirmation	10	view_emailconfirmation
41	Can add property	11	add_property
42	Can change property	11	change_property
43	Can delete property	11	delete_property
44	Can view property	11	view_property
45	Can add social account	12	add_socialaccount
46	Can change social account	12	change_socialaccount
47	Can delete social account	12	delete_socialaccount
48	Can view social account	12	view_socialaccount
49	Can add social application	13	add_socialapp
50	Can change social application	13	change_socialapp
51	Can delete social application	13	delete_socialapp
52	Can view social application	13	view_socialapp
53	Can add social application token	14	add_socialtoken
54	Can change social application token	14	change_socialtoken
55	Can delete social application token	14	delete_socialtoken
56	Can view social application token	14	view_socialtoken
57	Can add reservation	15	add_reservation
58	Can change reservation	15	change_reservation
59	Can delete reservation	15	delete_reservation
60	Can view reservation	15	view_reservation
61	Can add conversation	16	add_conversation
62	Can change conversation	16	change_conversation
63	Can delete conversation	16	delete_conversation
64	Can view conversation	16	view_conversation
65	Can add conversation message	17	add_conversationmessage
66	Can change conversation message	17	change_conversationmessage
67	Can delete conversation message	17	delete_conversationmessage
68	Can view conversation message	17	view_conversationmessage
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
\.


--
-- Data for Name: chat_conversation; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.chat_conversation (id, created_at, modified_at) FROM stdin;
66431a22-6493-4ba7-8324-1a7112d15fe2	2026-09-22 11:23:01.795433+00	2026-09-22 11:23:01.79544+00
749706cd-647f-4a1c-936e-3b5e7ef02644	2026-09-25 11:18:41.974141+00	2026-09-25 11:18:41.974153+00
\.


--
-- Data for Name: chat_conversation_users; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.chat_conversation_users (id, conversation_id, user_id) FROM stdin;
5	66431a22-6493-4ba7-8324-1a7112d15fe2	c3c53cab-a7d5-4212-a43e-46c378ad57cd
6	66431a22-6493-4ba7-8324-1a7112d15fe2	7cb4f977-9920-48df-ad96-dee74b3a6c5b
36	749706cd-647f-4a1c-936e-3b5e7ef02644	c3c53cab-a7d5-4212-a43e-46c378ad57cd
37	749706cd-647f-4a1c-936e-3b5e7ef02644	ffe24a94-1408-4072-9bc9-c41186ada984
\.


--
-- Data for Name: chat_conversationmessage; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.chat_conversationmessage (id, body, created_at, conversation_id, created_by_id, sent_to_id) FROM stdin;
58a6f464-887b-42e4-9789-b942bf06b3b3	Hi there	2026-09-22 11:23:20.694351+00	66431a22-6493-4ba7-8324-1a7112d15fe2	c3c53cab-a7d5-4212-a43e-46c378ad57cd	7cb4f977-9920-48df-ad96-dee74b3a6c5b
ee64bc32-acab-49b3-bac8-b93e36b6c8e1	hlw how are you	2026-09-24 11:57:23.858216+00	66431a22-6493-4ba7-8324-1a7112d15fe2	c3c53cab-a7d5-4212-a43e-46c378ad57cd	7cb4f977-9920-48df-ad96-dee74b3a6c5b
787013c5-fdf7-4156-8c06-f627b7ba21c5	Hi need to talk about the two bed room flat	2026-09-25 11:18:57.824502+00	749706cd-647f-4a1c-936e-3b5e7ef02644	c3c53cab-a7d5-4212-a43e-46c378ad57cd	ffe24a94-1408-4072-9bc9-c41186ada984
4c75dd48-2180-4b79-b1dd-3bcbcb889e9f	Sure, how can I help	2026-09-25 11:20:17.593557+00	749706cd-647f-4a1c-936e-3b5e7ef02644	ffe24a94-1408-4072-9bc9-c41186ada984	c3c53cab-a7d5-4212-a43e-46c378ad57cd
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-09-14 11:24:40.351605+00	db954d28-8701-42f2-b26a-a053e329f9ea	Property object (db954d28-8701-42f2-b26a-a053e329f9ea)	1	[{"added": {}}]	11	7cb4f977-9920-48df-ad96-dee74b3a6c5b
2	2026-09-14 17:29:57.540271+00	5794ff23-da0a-44ef-9c65-e2f45bd4836d	Property object (5794ff23-da0a-44ef-9c65-e2f45bd4836d)	1	[{"added": {}}]	11	7cb4f977-9920-48df-ad96-dee74b3a6c5b
3	2026-09-14 17:30:23.986182+00	db954d28-8701-42f2-b26a-a053e329f9ea	Property object (db954d28-8701-42f2-b26a-a053e329f9ea)	2	[{"changed": {"fields": ["Title"]}}]	11	7cb4f977-9920-48df-ad96-dee74b3a6c5b
4	2026-09-18 10:27:51.280858+00	94a789b9-6e5c-4a36-82fc-30b1eece19a8	Property object (94a789b9-6e5c-4a36-82fc-30b1eece19a8)	2	[]	11	7cb4f977-9920-48df-ad96-dee74b3a6c5b
5	2026-09-18 10:28:09.319205+00	94a789b9-6e5c-4a36-82fc-30b1eece19a8	Property object (94a789b9-6e5c-4a36-82fc-30b1eece19a8)	2	[{"changed": {"fields": ["Landlord"]}}]	11	7cb4f977-9920-48df-ad96-dee74b3a6c5b
6	2026-09-20 11:17:03.7615+00	1fb85aac-1c7c-45c9-9a22-4a19a8edc5f6	Reservation object (1fb85aac-1c7c-45c9-9a22-4a19a8edc5f6)	3		15	7cb4f977-9920-48df-ad96-dee74b3a6c5b
7	2026-09-22 10:57:55.387187+00	9246386d-6e07-4cea-b8f6-0e05633571eb	Conversation object (9246386d-6e07-4cea-b8f6-0e05633571eb)	1	[{"added": {}}]	16	7cb4f977-9920-48df-ad96-dee74b3a6c5b
8	2026-09-22 10:58:17.550697+00	8d55a6b3-f36e-4707-a2f8-d69450b8f15a	ConversationMessage object (8d55a6b3-f36e-4707-a2f8-d69450b8f15a)	1	[{"added": {}}]	17	7cb4f977-9920-48df-ad96-dee74b3a6c5b
9	2026-09-22 11:03:18.815097+00	8d55a6b3-f36e-4707-a2f8-d69450b8f15a	ConversationMessage object (8d55a6b3-f36e-4707-a2f8-d69450b8f15a)	2	[]	17	7cb4f977-9920-48df-ad96-dee74b3a6c5b
10	2026-09-22 11:04:26.569755+00	9246386d-6e07-4cea-b8f6-0e05633571eb	Conversation object (9246386d-6e07-4cea-b8f6-0e05633571eb)	3		16	7cb4f977-9920-48df-ad96-dee74b3a6c5b
11	2026-09-22 11:04:34.415732+00	e3540955-2aea-4d30-8b69-5d28e451ba67	Conversation object (e3540955-2aea-4d30-8b69-5d28e451ba67)	1	[{"added": {}}]	16	7cb4f977-9920-48df-ad96-dee74b3a6c5b
12	2026-09-22 11:04:51.481072+00	ffd9f310-029c-4d40-93cc-ec89344d2f21	ConversationMessage object (ffd9f310-029c-4d40-93cc-ec89344d2f21)	1	[{"added": {}}]	17	7cb4f977-9920-48df-ad96-dee74b3a6c5b
13	2026-09-22 11:14:57.186133+00	1	shefat.global@gmail.com	2	[]	9	7cb4f977-9920-48df-ad96-dee74b3a6c5b
14	2026-09-22 11:15:32.204116+00	1	shefat.global@gmail.com	2	[]	9	7cb4f977-9920-48df-ad96-dee74b3a6c5b
15	2026-09-22 11:22:29.581915+00	1	shefat.global@gmail.com	3		9	7cb4f977-9920-48df-ad96-dee74b3a6c5b
16	2026-09-22 11:22:34.8775+00	ffd9f310-029c-4d40-93cc-ec89344d2f21	ConversationMessage object (ffd9f310-029c-4d40-93cc-ec89344d2f21)	3		17	7cb4f977-9920-48df-ad96-dee74b3a6c5b
17	2026-09-22 11:22:43.977441+00	3298c6b6-ada4-4573-b1a2-bf72fce037a5	Conversation object (3298c6b6-ada4-4573-b1a2-bf72fce037a5)	1	[{"added": {}}]	16	7cb4f977-9920-48df-ad96-dee74b3a6c5b
18	2026-09-22 11:22:53.999503+00	e3540955-2aea-4d30-8b69-5d28e451ba67	Conversation object (e3540955-2aea-4d30-8b69-5d28e451ba67)	3		16	7cb4f977-9920-48df-ad96-dee74b3a6c5b
19	2026-09-22 11:22:56.395841+00	3298c6b6-ada4-4573-b1a2-bf72fce037a5	Conversation object (3298c6b6-ada4-4573-b1a2-bf72fce037a5)	3		16	7cb4f977-9920-48df-ad96-dee74b3a6c5b
20	2026-09-22 11:23:01.796997+00	66431a22-6493-4ba7-8324-1a7112d15fe2	Conversation object (66431a22-6493-4ba7-8324-1a7112d15fe2)	1	[{"added": {}}]	16	7cb4f977-9920-48df-ad96-dee74b3a6c5b
21	2026-09-22 11:23:20.694777+00	58a6f464-887b-42e4-9789-b942bf06b3b3	ConversationMessage object (58a6f464-887b-42e4-9789-b942bf06b3b3)	1	[{"added": {}}]	17	7cb4f977-9920-48df-ad96-dee74b3a6c5b
50	2026-09-25 06:44:33.352928+00	7cb4f977-9920-48df-ad96-dee74b3a6c5b	ishefat@gmail.com	2	[{"changed": {"fields": ["Name", "Avatar"]}}]	6	7cb4f977-9920-48df-ad96-dee74b3a6c5b
51	2026-09-25 09:42:35.813502+00	c3c53cab-a7d5-4212-a43e-46c378ad57cd	shefat.global@gmail.com	2	[{"changed": {"fields": ["Name", "Avatar"]}}]	6	7cb4f977-9920-48df-ad96-dee74b3a6c5b
52	2026-09-25 11:07:45.471968+00	ffe24a94-1408-4072-9bc9-c41186ada984	ishefat@outlook.com	2	[{"changed": {"fields": ["Name", "Avatar"]}}]	6	7cb4f977-9920-48df-ad96-dee74b3a6c5b
53	2026-09-27 09:23:08.050686+00	db954d28-8701-42f2-b26a-a053e329f9ea	Property object (db954d28-8701-42f2-b26a-a053e329f9ea)	2	[{"changed": {"fields": ["Category"]}}]	11	7cb4f977-9920-48df-ad96-dee74b3a6c5b
54	2026-09-27 09:23:16.365503+00	94a789b9-6e5c-4a36-82fc-30b1eece19a8	Property object (94a789b9-6e5c-4a36-82fc-30b1eece19a8)	2	[{"changed": {"fields": ["Category"]}}]	11	7cb4f977-9920-48df-ad96-dee74b3a6c5b
55	2026-09-27 09:23:34.682266+00	5794ff23-da0a-44ef-9c65-e2f45bd4836d	Property object (5794ff23-da0a-44ef-9c65-e2f45bd4836d)	2	[{"changed": {"fields": ["Category"]}}]	11	7cb4f977-9920-48df-ad96-dee74b3a6c5b
56	2026-09-27 09:23:42.717534+00	34a853ee-2453-41c6-ad3e-79863d181122	Property object (34a853ee-2453-41c6-ad3e-79863d181122)	2	[{"changed": {"fields": ["Category"]}}]	11	7cb4f977-9920-48df-ad96-dee74b3a6c5b
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	useraccount	user
7	authtoken	token
8	authtoken	tokenproxy
9	account	emailaddress
10	account	emailconfirmation
11	property	property
12	socialaccount	socialaccount
13	socialaccount	socialapp
14	socialaccount	socialtoken
15	property	reservation
16	chat	conversation
17	chat	conversationmessage
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-09-12 17:33:25.123295+00
2	contenttypes	0002_remove_content_type_name	2026-09-12 17:33:25.128396+00
3	auth	0001_initial	2026-09-12 17:33:25.249001+00
4	auth	0002_alter_permission_name_max_length	2026-09-12 17:33:25.253783+00
5	auth	0003_alter_user_email_max_length	2026-09-12 17:33:25.258424+00
6	auth	0004_alter_user_username_opts	2026-09-12 17:33:25.262951+00
7	auth	0005_alter_user_last_login_null	2026-09-12 17:33:25.267968+00
8	auth	0006_require_contenttypes_0002	2026-09-12 17:33:25.271076+00
9	auth	0007_alter_validators_add_error_messages	2026-09-12 17:33:25.276331+00
10	auth	0008_alter_user_username_max_length	2026-09-12 17:33:25.281381+00
11	auth	0009_alter_user_last_name_max_length	2026-09-12 17:33:25.28605+00
12	auth	0010_alter_group_name_max_length	2026-09-12 17:33:25.291507+00
13	auth	0011_update_proxy_permissions	2026-09-12 17:33:25.296989+00
14	auth	0012_alter_user_first_name_max_length	2026-09-12 17:33:25.30214+00
15	useraccount	0001_initial	2026-09-12 17:33:25.373456+00
16	admin	0001_initial	2026-09-12 17:33:25.412861+00
17	admin	0002_logentry_remove_auto_add	2026-09-12 17:33:25.420278+00
18	admin	0003_logentry_add_action_flag_choices	2026-09-12 17:33:25.426806+00
19	sessions	0001_initial	2026-09-12 17:33:25.452002+00
20	account	0001_initial	2026-09-13 10:28:32.825966+00
21	account	0002_email_max_length	2026-09-13 10:28:32.834962+00
22	account	0003_alter_emailaddress_create_unique_verified_email	2026-09-13 10:28:32.853808+00
23	account	0004_alter_emailaddress_drop_unique_email	2026-09-13 10:28:32.868539+00
24	account	0005_emailaddress_idx_upper_email	2026-09-13 10:28:32.881757+00
25	account	0006_emailaddress_lower	2026-09-13 10:28:32.891163+00
26	account	0007_emailaddress_idx_email	2026-09-13 10:28:32.909983+00
27	account	0008_emailaddress_unique_primary_email_fixup	2026-09-13 10:28:32.918947+00
28	account	0009_emailaddress_unique_primary_email	2026-09-13 10:28:32.93032+00
29	authtoken	0001_initial	2026-09-13 10:28:32.956941+00
30	authtoken	0002_auto_20160226_1747	2026-09-13 10:28:32.974665+00
31	authtoken	0003_tokenproxy	2026-09-13 10:28:32.979646+00
32	authtoken	0004_alter_tokenproxy_options	2026-09-13 10:28:32.98437+00
33	property	0001_initial	2026-09-13 12:00:59.026902+00
34	socialaccount	0001_initial	2026-09-15 09:31:22.841233+00
35	socialaccount	0002_token_max_lengths	2026-09-15 09:31:22.858709+00
36	socialaccount	0003_extra_data_default_dict	2026-09-15 09:31:22.865398+00
37	socialaccount	0004_app_provider_id_settings	2026-09-15 09:31:22.878534+00
38	socialaccount	0005_socialtoken_nullable_app	2026-09-15 09:31:22.896195+00
39	socialaccount	0006_alter_socialaccount_extra_data	2026-09-15 09:31:22.925177+00
40	property	0002_reservation	2026-09-19 06:38:03.177682+00
41	property	0003_property_favorited	2026-09-21 15:24:50.669169+00
74	chat	0001_initial	2026-09-22 06:33:47.694784+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
ghagq12kyuipqzbz9nd8r09nkvfdqalz	.eJxVzDsOwjAQRdG9uMaW4884pqRnDdGMZ0wCKJHyqRB7h0gpoH73vJfqcFv7bltk7gZWZ5UKhZpT0jk7q0PLVSNn0CySAnmEEkmdfhlheci4W77jeJtMmcZ1HsjsiTnWxVwnluflaP8Oelz6rxZibMQWkhSZoo0tIJPLyXkKNtbKDbSxQiAWj1iycwl9DQBA1TKq9wdrNkKh:1x64es:AJt4kMo6s4xdgxbzW7yMyMLPaAqygYr6ijTLxDQmEqY	2026-09-28 11:15:34.637413+00
y68ijome7itszhxuw95n75veow2kg10z	.eJxVzDsOwjAQRdG9uMaW4884pqRnDdGMZ0wCKJHyqRB7h0gpoH73vJfqcFv7bltk7gZWZ5UKhZpT0jk7q0PLVSNn0CySAnmEEkmdfhlheci4W77jeJtMmcZ1HsjsiTnWxVwnluflaP8Oelz6rxZibMQWkhSZoo0tIJPLyXkKNtbKDbSxQiAWj1iycwl9DQBA1TKq9wdrNkKh:1x6ALF:788nt6Kh6MUaojCrbzj8D7oLXxfvmqueroOTSdH0vEA	2026-09-28 17:19:41.15295+00
u6ob9ejuy68xmkfw19jrm5s30s5s170y	.eJxVzDsOwjAQRdG9uMaW4884pqRnDdGMZ0wCKJHyqRB7h0gpoH73vJfqcFv7bltk7gZWZ5UKhZpT0jk7q0PLVSNn0CySAnmEEkmdfhlheci4W77jeJtMmcZ1HsjsiTnWxVwnluflaP8Oelz6rxZibMQWkhSZoo0tIJPLyXkKNtbKDbSxQiAWj1iycwl9DQBA1TKq9wdrNkKh:1x6Pkq:ap0Y-gIpvup5rbIzZ9GpFuuPwN7K4sO-WDn16WNKKkA	2026-09-29 09:47:08.098956+00
eonhe92zduq2yjctc6cdz3uvo6p5pcqy	.eJxVjTsOwjAQBe_imkSO7Y0TSnrOYK1318QQHCkfGsTdASlN6jcz762QaNrKGl4y55SFgzwxj-pctnE8qYDbOoRtkTlkVmdFlsASxgo9Q-VMYyp0VirXkvUdMnhiddAi0kPK3-U7lttU01TWOcf6j9T7utTXiWW87OwhMOAy_GyHHbakk2hgJE8GovRaG_P7T4atbnxP3mAD1ERA6_oOsNXJx-jBuKQ-XxbMTLM:1x6R3T:UR8tuY9Os3kphXqjOzdzDTc1qPHEAx1xoHPk7-SGmD8	2026-09-29 11:10:27.508545+00
7jtppf1ul7q41161nx2uitoxv43j0pwd	.eJxVjUsOgzAMBe-SdYkSJ8bQZfc9A3LspPQjkPisqt69ILFo129m3tt0vC59t8556u5qzkaCYBBOFZNiFcFDxTHkKtYSqGFFEjWnXy2xPPOwu_rg4TZaGYdluie7I_ZYZ3sdNb8uB_sX6HnuNztyw7W4kh0qCwlgyq1zANt_AQ3OUysE7FF8Qg6xbZBrVyglQojFfL4zYUFN:1x6iEC:Lt1833mu0QmHBij89Czsbw8DZ0ZMnEXg-TbQt8tTUr8	2026-09-30 05:30:40.345545+00
8qnh5i1d0fcjawp9kndw0237a5c0d1uy	.eJxVjUsOgzAMBe-SdYkSJ8bQZfc9A3LspPQjkPisqt69ILFo129m3tt0vC59t8556u5qzkaCYBBOFZNiFcFDxTHkKtYSqGFFEjWnXy2xPPOwu_rg4TZaGYdluie7I_ZYZ3sdNb8uB_sX6HnuNztyw7W4kh0qCwlgyq1zANt_AQ3OUysE7FF8Qg6xbZBrVyglQojFfL4zYUFN:1x6mCn:qBzplAt1yDg24hD0rrtqqejg-Jefd7wscskbbvS3JT8	2026-09-30 09:45:29.568242+00
xzydekop986efums5etyft3nwzht2n5l	.eJxVjUsOgzAMBe-SdYkSJ8bQZfc9A3LspPQjkPisqt69ILFo129m3tt0vC59t8556u5qzkaCYBBOFZNiFcFDxTHkKtYSqGFFEjWnXy2xPPOwu_rg4TZaGYdluie7I_ZYZ3sdNb8uB_sX6HnuNztyw7W4kh0qCwlgyq1zANt_AQ3OUysE7FF8Qg6xbZBrVyglQojFfL4zYUFN:1x6n3Q:ZYPiLT8yE4MYYLtu7Kgx_d3_zpYMt-iirNCUpSDE1aE	2026-09-30 10:39:52.025878+00
4olyoria3lhx0t2ajophpveuqna9a5rb	.eJxVjUsOgzAMBe-SdYkSJ8bQZfc9A3LspPQjkPisqt69ILFo129m3tt0vC59t8556u5qzkaCYBBOFZNiFcFDxTHkKtYSqGFFEjWnXy2xPPOwu_rg4TZaGYdluie7I_ZYZ3sdNb8uB_sX6HnuNztyw7W4kh0qCwlgyq1zANt_AQ3OUysE7FF8Qg6xbZBrVyglQojFfL4zYUFN:1x799S:MXQM63cLPElfSBoRzG35ubd23Cyn_QRnNRZTQCXgK6g	2026-10-01 10:15:34.328476+00
r54pph6cdsu53sxy0tkqm65ckqrjd7vo	.eJxVzDsOwjAQRdG9uMaW4884pqRnDdGMZ0wCKJHyqRB7h0gpoH73vJfqcFv7bltk7gZWZ5UKhZpT0jk7q0PLVSNn0CySAnmEEkmdfhlheci4W77jeJtMmcZ1HsjsiTnWxVwnluflaP8Oelz6rxZibMQWkhSZoo0tIJPLyXkKNtbKDbSxQiAWj1iycwl9DQBA1TKq9wdrNkKh:1x7VoW:4TfCHRJ5nQjVZH3LCefKb79gI4hSevgbHzQ0DG5htHo	2026-10-02 10:27:28.250267+00
9j9k6e4zg772q2w3r84kiyine4vtqym5	.eJxVjUsOgzAMBe-SdYkSJ8bQZfc9A3LspPQjkPisqt69ILFo129m3tt0vC59t8556u5qzkaCYBBOFZNiFcFDxTHkKtYSqGFFEjWnXy2xPPOwu_rg4TZaGYdluie7I_ZYZ3sdNb8uB_sX6HnuNztyw7W4kh0qCwlgyq1zANt_AQ3OUysE7FF8Qg6xbZBrVyglQojFfL4zYUFN:1x8F6V:t-MxoJsYRP_5VrzdX7awfzMf2Sx0gmh6eP7yeaIB73s	2026-10-04 10:49:03.874138+00
iqq9v06oabf1t18acle75hjy7xmy0dy6	.eJxVjUsOgzAMBe-SdYkSJ8bQZfc9A3LspPQjkPisqt69ILFo129m3tt0vC59t8556u5qzkaCYBBOFZNiFcFDxTHkKtYSqGFFEjWnXy2xPPOwu_rg4TZaGYdluie7I_ZYZ3sdNb8uB_sX6HnuNztyw7W4kh0qCwlgyq1zANt_AQ3OUysE7FF8Qg6xbZBrVyglQojFfL4zYUFN:1x8aiv:qXbJnGciXPqGzylc9ar-7SotoCSQ4LrxJq6lktkx0as	2026-10-05 09:54:09.361239+00
4tfmjt3dteoxoa84nohons72c1pf418g	.eJxVjUsOgzAMBe-SdYkSJ8bQZfc9A3LspPQjkPisqt69ILFo129m3tt0vC59t8556u5qzkaCYBBOFZNiFcFDxTHkKtYSqGFFEjWnXy2xPPOwu_rg4TZaGYdluie7I_ZYZ3sdNb8uB_sX6HnuNztyw7W4kh0qCwlgyq1zANt_AQ3OUysE7FF8Qg6xbZBrVyglQojFfL4zYUFN:1x8bol:-rFzPTXai9WMjYzfTcEtHV13YcvB-B9Vdn9f0w9peEw	2026-10-05 11:04:15.478017+00
ffu0mctjdqmd2qn8zhff897t6gq3cz0l	.eJxVjUsOgzAMBe-SdYkSJ8bQZfc9A3LspPQjkPisqt69ILFo129m3tt0vC59t8556u5qzkaCYBBOFZNiFcFDxTHkKtYSqGFFEjWnXy2xPPOwu_rg4TZaGYdluie7I_ZYZ3sdNb8uB_sX6HnuNztyw7W4kh0qCwlgyq1zANt_AQ3OUysE7FF8Qg6xbZBrVyglQojFfL4zYUFN:1x8gYw:x0SJHQgdE60LJW7O9b3JoXt2ISH-HkXJm0EWGPItoqU	2026-10-05 16:08:14.389131+00
de1w5w6kctirq7ivjb8nirylis9erorv	.eJxVjUsOgzAMBe-SdYkSJ8bQZfc9A3LspPQjkPisqt69ILFo129m3tt0vC59t8556u5qzkaCYBBOFZNiFcFDxTHkKtYSqGFFEjWnXy2xPPOwu_rg4TZaGYdluie7I_ZYZ3sdNb8uB_sX6HnuNztyw7W4kh0qCwlgyq1zANt_AQ3OUysE7FF8Qg6xbZBrVyglQojFfL4zYUFN:1x8gv8:faS1SJVFvTolkeO3ROdCGzfsw5cp9lqzWgZTg7AlSQI	2026-10-05 16:31:10.647571+00
fywztebghvx6upyxyr8jvgmipxhghwbc	.eJxVjUsOgzAMBe-SdYkSJ8bQZfc9A3LspPQjkPisqt69ILFo129m3tt0vC59t8556u5qzkaCYBBOFZNiFcFDxTHkKtYSqGFFEjWnXy2xPPOwu_rg4TZaGYdluie7I_ZYZ3sdNb8uB_sX6HnuNztyw7W4kh0qCwlgyq1zANt_AQ3OUysE7FF8Qg6xbZBrVyglQojFfL4zYUFN:1x8sN4:FKcbz8ZxF4bOZ9o2R0taGjMUnJgIPHVUafa8dSk7qHE	2026-10-06 04:44:46.007829+00
21j7v0qnkmtzfgbbwyahhb5zudw09f25	.eJxVzDsOwjAQRdG9uMaW4884pqRnDdGMZ0wCKJHyqRB7h0gpoH73vJfqcFv7bltk7gZWZ5UKhZpT0jk7q0PLVSNn0CySAnmEEkmdfhlheci4W77jeJtMmcZ1HsjsiTnWxVwnluflaP8Oelz6rxZibMQWkhSZoo0tIJPLyXkKNtbKDbSxQiAWj1iycwl9DQBA1TKq9wdrNkKh:1x8sPH:Zh-d6en8omERwCZiM6yK12xmPJdtgbauIqAQQcjgdEE	2026-10-06 04:47:03.500986+00
xj39md3984l99yaij5jsluxplfq2tymj	.eJxVjUsOgzAMBe-SdYkSJ8bQZfc9A3LspPQjkPisqt69ILFo129m3tt0vC59t8556u5qzkaCYBBOFZNiFcFDxTHkKtYSqGFFEjWnXy2xPPOwu_rg4TZaGYdluie7I_ZYZ3sdNb8uB_sX6HnuNztyw7W4kh0qCwlgyq1zANt_AQ3OUysE7FF8Qg6xbZBrVyglQojFfL4zYUFN:1x8yIF:gRt8COUdV6_cEDRf_91eutZK_PyuZRRrF2yGQ_Qevrs	2026-10-06 11:04:11.408068+00
9kfl9nmqlid7w10daae145rtjy1fxzd1	.eJxVjUsOgzAMBe-SdYkSJ8bQZfc9A3LspPQjkPisqt69ILFo129m3tt0vC59t8556u5qzkaCYBBOFZNiFcFDxTHkKtYSqGFFEjWnXy2xPPOwu_rg4TZaGYdluie7I_ZYZ3sdNb8uB_sX6HnuNztyw7W4kh0qCwlgyq1zANt_AQ3OUysE7FF8Qg6xbZBrVyglQojFfL4zYUFN:1x9M2Q:bDtopb9Z5L-7OS5ODX82T7C_gPx2YfpHRPoWnzLZq9o	2026-10-07 12:25:26.490981+00
oc5wj3von26951fh86yoi8mh6ql9bzd5	.eJxVjUsOgzAMBe-SdYkSJ8bQZfc9A3LspPQjkPisqt69ILFo129m3tt0vC59t8556u5qzkaCYBBOFZNiFcFDxTHkKtYSqGFFEjWnXy2xPPOwu_rg4TZaGYdluie7I_ZYZ3sdNb8uB_sX6HnuNztyw7W4kh0qCwlgyq1zANt_AQ3OUysE7FF8Qg6xbZBrVyglQojFfL4zYUFN:1x9bpA:aXzC9f8MTfo8Jy_7YBvrYsTZDf1xNz19kgLIc5OdgSA	2026-10-08 05:16:48.224135+00
boo3v0m7txuw8nf9tek5jw0gavahxr8k	.eJxVjUsOgzAMBe-SdYkSJ8bQZfc9A3LspPQjkPisqt69ILFo129m3tt0vC59t8556u5qzkaCYBBOFZNiFcFDxTHkKtYSqGFFEjWnXy2xPPOwu_rg4TZaGYdluie7I_ZYZ3sdNb8uB_sX6HnuNztyw7W4kh0qCwlgyq1zANt_AQ3OUysE7FF8Qg6xbZBrVyglQojFfL4zYUFN:1x9cq3:roDoJAtpNr8t4NTUe5JuIFen6FZpJtkocpN_qNBEGIA	2026-10-08 06:21:47.892226+00
dc55msqbqht58vv1ckinjdcnvw03xw7f	.eJxVjUsOgzAMBe-SdYkSJ8bQZfc9A3LspPQjkPisqt69ILFo129m3tt0vC59t8556u5qzkaCYBBOFZNiFcFDxTHkKtYSqGFFEjWnXy2xPPOwu_rg4TZaGYdluie7I_ZYZ3sdNb8uB_sX6HnuNztyw7W4kh0qCwlgyq1zANt_AQ3OUysE7FF8Qg6xbZBrVyglQojFfL4zYUFN:1x9hnj:tueW2pyXxGolUgkNnOe4vYpIPaD3XkBAG_hz_Wf_HPE	2026-10-08 11:39:43.218034+00
fz3tob0e77zc22j5b6qs7k78f6njlrmp	.eJxVjUsOgzAMBe-SdYkSJ8bQZfc9A3LspPQjkPisqt69ILFo129m3tt0vC59t8556u5qzkaCYBBOFZNiFcFDxTHkKtYSqGFFEjWnXy2xPPOwu_rg4TZaGYdluie7I_ZYZ3sdNb8uB_sX6HnuNztyw7W4kh0qCwlgyq1zANt_AQ3OUysE7FF8Qg6xbZBrVyglQojFfL4zYUFN:1x9zgF:cLO-GDiPZmAsBJYuQ8FJWYCznKTZScvgJMD7ajOEMm8	2026-10-09 06:45:11.803963+00
ictdt6wkkq9ujjt6dqpthrlz20esemg2	.eJxVjUsOgzAMBe-SdYkSJ8bQZfc9A3LspPQjkPisqt69ILFo129m3tt0vC59t8556u5qzkaCYBBOFZNiFcFDxTHkKtYSqGFFEjWnXy2xPPOwu_rg4TZaGYdluie7I_ZYZ3sdNb8uB_sX6HnuNztyw7W4kh0qCwlgyq1zANt_AQ3OUysE7FF8Qg6xbZBrVyglQojFfL4zYUFN:1xA2Sf:yfugIm5_P98lwvgBYL4CasiYWr8Z1FJGTVOuiUulLxg	2026-10-09 09:43:21.797391+00
5dhvlsljqqvg2k7kdfdnxmx13qgzwlim	.eJxVjTtuwzAQBe_COhL4WYqkS_c5A7HLXUZMFArQJ43huwcC3Lh-M_MeCktZz37kP9labcJZfrEt6tbPZflQGc9jzucuW26sbqpWsYAJBgM6DqCDHRKVNBQwJk7ImCKoN42w_Ei_XP7G_rWOZe3H1mi8kPG17uPnyrLcX-xbYMZ9vp4ZxRlrgqucDHmqln0AF8hGAO1RoFiqfnJQIGqnE5MQFB9Ek0yinv-jtEx2:1xA3fB:U1yQWVPZ8EpifztyZb_f6El-NFMATRvWYIiR2a-Yoqs	2026-10-09 11:00:21.234144+00
rmzv5pbbnmpbigbgq53pspfqlcgr4eq3	.eJxVjUsOgzAMBe-SdYkSJ8bQZfc9A3LspPQjkPisqt69ILFo129m3tt0vC59t8556u5qzkaCYBBOFZNiFcFDxTHkKtYSqGFFEjWnXy2xPPOwu_rg4TZaGYdluie7I_ZYZ3sdNb8uB_sX6HnuNztyw7W4kh0qCwlgyq1zANt_AQ3OUysE7FF8Qg6xbZBrVyglQojFfL4zYUFN:1xA3n2:PmZOqNcF6SGU91cS-olPdfQKHG-LhDalKugh2t1ie_w	2026-10-09 11:08:28.854971+00
gardqtjt83cyj7qw2sx1ve88jsr5y4wo	.eJxVjTkOwjAQRe_iGltexrFNSc8ZohnPmLAokbJUiLujSCmg_u-9_1Y9buvQb4vM_Z3VWbUmHrCAdmCzBpu8LlSLruBc7pCxZFCnX42wPmXcXX7geJtMncZ1vpPZEXOsi7lOLK_Lwf4FBlyG_ZlRgvMuhcbFUaTmOSYIiXwGsBEFqqcWuwAVsg22MAlBjUksSSfq8wXASUEQ:1xA3yC:qsFh4PDQPWSBmSTNVz7QJLFSQR-X-RbJUb9sjVWBHcM	2026-10-09 11:20:00.216841+00
w8mt6bvwf6amws2xfmcg392q0gzh3wbb	.eJxVjUsOgzAMBe-SdYkSJ8bQZfc9A3LspPQjkPisqt69ILFo129m3tt0vC59t8556u5qzkaCYBBOFZNiFcFDxTHkKtYSqGFFEjWnXy2xPPOwu_rg4TZaGYdluie7I_ZYZ3sdNb8uB_sX6HnuNztyw7W4kh0qCwlgyq1zANt_AQ3OUysE7FF8Qg6xbZBrVyglQojFfL4zYUFN:1xAnXI:mIhH6UmQLNTuezR8FHSAvvsVhEtB6zyuImQEKEZRQ3w	2026-10-11 11:59:16.430019+00
lk8e0pn2kv21ty93dvjijdqb56j01kkb	.eJxVjUsOgzAMBe-SdYkSJ8bQZfc9A3LspPQjkPisqt69ILFo129m3tt0vC59t8556u5qzkaCYBBOFZNiFcFDxTHkKtYSqGFFEjWnXy2xPPOwu_rg4TZaGYdluie7I_ZYZ3sdNb8uB_sX6HnuNztyw7W4kh0qCwlgyq1zANt_AQ3OUysE7FF8Qg6xbZBrVyglQojFfL4zYUFN:1xB30K:lSlvadrzqIPKftRer-48aI-FNOPmoVcSr8vqJyHWbUI	2026-10-12 04:30:16.045754+00
\.


--
-- Data for Name: property_property; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.property_property (id, title, description, price_per_night, bedrooms, bathrooms, guests, country, country_code, category, image, created_at, landlord_id) FROM stdin;
db954d28-8701-42f2-b26a-a053e329f9ea	One Storied	Tempora velit numqua Tempora velit numqua Tempora velit numqua	240	2	2	4	Bangladesh	018	beach	uploads/properties/beach_1.jpg	2026-09-14 11:24:40.348207+00	7cb4f977-9920-48df-ad96-dee74b3a6c5b
94a789b9-6e5c-4a36-82fc-30b1eece19a8	Studio flat	Sunt proident quas	25	1	1	1	Afghanistan	AF	beach	uploads/properties/wood-paneling-apartment.jpg	2026-09-17 10:34:45.06737+00	7cb4f977-9920-48df-ad96-dee74b3a6c5b
5794ff23-da0a-44ef-9c65-e2f45bd4836d	Flat Sqft	Veniam qui est obca	200	2	2	4	bangladesh	018	villas	uploads/properties/beach_1_U9T3G4A.jpg	2026-09-14 17:29:57.539375+00	7cb4f977-9920-48df-ad96-dee74b3a6c5b
34a853ee-2453-41c6-ad3e-79863d181122	Two Bed Room Flat	Two bed, main road	20	2	1	4	Bangladesh	BD	tiny_homes	uploads/properties/images.jpg	2026-09-25 11:06:57.799158+00	ffe24a94-1408-4072-9bc9-c41186ada984
\.


--
-- Data for Name: property_property_favorited; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.property_property_favorited (id, property_id, user_id) FROM stdin;
7	db954d28-8701-42f2-b26a-a053e329f9ea	c3c53cab-a7d5-4212-a43e-46c378ad57cd
8	5794ff23-da0a-44ef-9c65-e2f45bd4836d	c3c53cab-a7d5-4212-a43e-46c378ad57cd
\.


--
-- Data for Name: property_reservation; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.property_reservation (id, start_date, end_date, number_of_nights, guests, total_price, created_at, created_by_id, property_id) FROM stdin;
24ee4e10-0a34-4371-8438-70115e3ee212	2026-09-20	2026-09-22	2	1	420	2026-09-20 11:16:51.772109+00	c3c53cab-a7d5-4212-a43e-46c378ad57cd	5794ff23-da0a-44ef-9c65-e2f45bd4836d
e837756e-224b-4b45-a0c5-c59c6917aef3	2026-09-20	2026-09-22	2	1	420	2026-09-20 11:18:42.317174+00	c3c53cab-a7d5-4212-a43e-46c378ad57cd	5794ff23-da0a-44ef-9c65-e2f45bd4836d
d0c3e381-6719-4588-89ee-c67d30807bd4	2026-09-23	2026-09-24	1	2	210	2026-09-22 04:45:15.433036+00	c3c53cab-a7d5-4212-a43e-46c378ad57cd	5794ff23-da0a-44ef-9c65-e2f45bd4836d
a970cefc-77a1-449e-bfe6-ff98217a8243	2026-09-23	2026-09-24	1	2	210	2026-09-22 04:45:17.13964+00	c3c53cab-a7d5-4212-a43e-46c378ad57cd	5794ff23-da0a-44ef-9c65-e2f45bd4836d
\.


--
-- Data for Name: socialaccount_socialaccount; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.socialaccount_socialaccount (id, provider, uid, last_login, date_joined, extra_data, user_id) FROM stdin;
\.


--
-- Data for Name: socialaccount_socialapp; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.socialaccount_socialapp (id, provider, name, client_id, secret, key, provider_id, settings) FROM stdin;
\.


--
-- Data for Name: socialaccount_socialtoken; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.socialaccount_socialtoken (id, token, token_secret, expires_at, account_id, app_id) FROM stdin;
\.


--
-- Data for Name: useraccount_user; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.useraccount_user (password, id, email, name, avatar, is_active, is_superuser, is_staff, date_joined, last_login) FROM stdin;
pbkdf2_sha256$1000000$yXt9gNlYnfOPcP95HXRZ4f$zxPgxjE1b5tSZvq/wYwtnN/P4z/fiAuRWRX5PN11Alc=	7cb4f977-9920-48df-ad96-dee74b3a6c5b	ishefat@gmail.com	Islam	uploads/avatars/shefat.jpeg	t	t	t	2026-09-14 10:43:31.391538+00	2026-09-22 04:47:03+00
pbkdf2_sha256$1000000$R9iiXDaXH4O1KxHDKnw7qr$8cldnZFSEOTO3yDo8vFYEXo6Oyhp5CFuijp6EjQK99A=	ffe24a94-1408-4072-9bc9-c41186ada984	ishefat@outlook.com	Robin	uploads/avatars/fbprofile.jpg	t	f	f	2026-09-25 11:00:21.19595+00	2026-09-25 11:20:00.211761+00
pbkdf2_sha256$1000000$JTzC9dX69cB69iec7c4JdM$YDwp5ennHOZV0FNvod8VBXY+mu0rAyT7P15zGF0knw4=	c3c53cab-a7d5-4212-a43e-46c378ad57cd	shefat.global@gmail.com	Shefat	uploads/avatars/engr_robin.png	t	f	f	2026-09-15 11:10:27.469626+00	2026-09-28 04:30:16.039954+00
\.


--
-- Data for Name: useraccount_user_groups; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.useraccount_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: useraccount_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgresuser
--

COPY public.useraccount_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgresuser
--

SELECT pg_catalog.setval('public.account_emailaddress_id_seq', 2, true);


--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgresuser
--

SELECT pg_catalog.setval('public.account_emailconfirmation_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgresuser
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgresuser
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgresuser
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 68, true);


--
-- Name: chat_conversation_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgresuser
--

SELECT pg_catalog.setval('public.chat_conversation_users_id_seq', 37, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgresuser
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 56, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgresuser
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 17, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgresuser
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 74, true);


--
-- Name: property_property_favorited_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgresuser
--

SELECT pg_catalog.setval('public.property_property_favorited_id_seq', 8, true);


--
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgresuser
--

SELECT pg_catalog.setval('public.socialaccount_socialaccount_id_seq', 1, false);


--
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgresuser
--

SELECT pg_catalog.setval('public.socialaccount_socialapp_id_seq', 1, false);


--
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgresuser
--

SELECT pg_catalog.setval('public.socialaccount_socialtoken_id_seq', 1, false);


--
-- Name: useraccount_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgresuser
--

SELECT pg_catalog.setval('public.useraccount_user_groups_id_seq', 1, false);


--
-- Name: useraccount_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgresuser
--

SELECT pg_catalog.setval('public.useraccount_user_user_permissions_id_seq', 1, false);


--
-- Name: account_emailaddress account_emailaddress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_pkey PRIMARY KEY (id);


--
-- Name: account_emailaddress account_emailaddress_user_id_email_987c8728_uniq; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_email_987c8728_uniq UNIQUE (user_id, email);


--
-- Name: account_emailconfirmation account_emailconfirmation_key_key; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_key_key UNIQUE (key);


--
-- Name: account_emailconfirmation account_emailconfirmation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: chat_conversation chat_conversation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.chat_conversation
    ADD CONSTRAINT chat_conversation_pkey PRIMARY KEY (id);


--
-- Name: chat_conversation_users chat_conversation_users_conversation_id_user_id_83095ff4_uniq; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.chat_conversation_users
    ADD CONSTRAINT chat_conversation_users_conversation_id_user_id_83095ff4_uniq UNIQUE (conversation_id, user_id);


--
-- Name: chat_conversation_users chat_conversation_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.chat_conversation_users
    ADD CONSTRAINT chat_conversation_users_pkey PRIMARY KEY (id);


--
-- Name: chat_conversationmessage chat_conversationmessage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.chat_conversationmessage
    ADD CONSTRAINT chat_conversationmessage_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: property_property_favorited property_property_favorited_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.property_property_favorited
    ADD CONSTRAINT property_property_favorited_pkey PRIMARY KEY (id);


--
-- Name: property_property_favorited property_property_favorited_property_id_user_id_c786450b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.property_property_favorited
    ADD CONSTRAINT property_property_favorited_property_id_user_id_c786450b_uniq UNIQUE (property_id, user_id);


--
-- Name: property_property property_property_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.property_property
    ADD CONSTRAINT property_property_pkey PRIMARY KEY (id);


--
-- Name: property_reservation property_reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.property_reservation
    ADD CONSTRAINT property_reservation_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_provider_uid_fc810c6e_uniq; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_provider_uid_fc810c6e_uniq UNIQUE (provider, uid);


--
-- Name: socialaccount_socialapp socialaccount_socialapp_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.socialaccount_socialapp
    ADD CONSTRAINT socialaccount_socialapp_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialtoken socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq UNIQUE (app_id, account_id);


--
-- Name: socialaccount_socialtoken socialaccount_socialtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_pkey PRIMARY KEY (id);


--
-- Name: useraccount_user useraccount_user_email_key; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.useraccount_user
    ADD CONSTRAINT useraccount_user_email_key UNIQUE (email);


--
-- Name: useraccount_user_groups useraccount_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.useraccount_user_groups
    ADD CONSTRAINT useraccount_user_groups_pkey PRIMARY KEY (id);


--
-- Name: useraccount_user_groups useraccount_user_groups_user_id_group_id_793452f9_uniq; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.useraccount_user_groups
    ADD CONSTRAINT useraccount_user_groups_user_id_group_id_793452f9_uniq UNIQUE (user_id, group_id);


--
-- Name: useraccount_user useraccount_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.useraccount_user
    ADD CONSTRAINT useraccount_user_pkey PRIMARY KEY (id);


--
-- Name: useraccount_user_user_permissions useraccount_user_user_pe_user_id_permission_id_47dceb51_uniq; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.useraccount_user_user_permissions
    ADD CONSTRAINT useraccount_user_user_pe_user_id_permission_id_47dceb51_uniq UNIQUE (user_id, permission_id);


--
-- Name: useraccount_user_user_permissions useraccount_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.useraccount_user_user_permissions
    ADD CONSTRAINT useraccount_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: account_emailaddress_email_03be32b2; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX account_emailaddress_email_03be32b2 ON public.account_emailaddress USING btree (email);


--
-- Name: account_emailaddress_email_03be32b2_like; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX account_emailaddress_email_03be32b2_like ON public.account_emailaddress USING btree (email varchar_pattern_ops);


--
-- Name: account_emailaddress_user_id_2c513194; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX account_emailaddress_user_id_2c513194 ON public.account_emailaddress USING btree (user_id);


--
-- Name: account_emailconfirmation_email_address_id_5b7f8c58; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX account_emailconfirmation_email_address_id_5b7f8c58 ON public.account_emailconfirmation USING btree (email_address_id);


--
-- Name: account_emailconfirmation_key_f43612bd_like; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX account_emailconfirmation_key_f43612bd_like ON public.account_emailconfirmation USING btree (key varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: chat_conversation_users_conversation_id_4c0fbe59; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX chat_conversation_users_conversation_id_4c0fbe59 ON public.chat_conversation_users USING btree (conversation_id);


--
-- Name: chat_conversation_users_user_id_37f0921c; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX chat_conversation_users_user_id_37f0921c ON public.chat_conversation_users USING btree (user_id);


--
-- Name: chat_conversationmessage_conversation_id_cf6c6293; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX chat_conversationmessage_conversation_id_cf6c6293 ON public.chat_conversationmessage USING btree (conversation_id);


--
-- Name: chat_conversationmessage_created_by_id_312d8431; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX chat_conversationmessage_created_by_id_312d8431 ON public.chat_conversationmessage USING btree (created_by_id);


--
-- Name: chat_conversationmessage_sent_to_id_6a38f604; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX chat_conversationmessage_sent_to_id_6a38f604 ON public.chat_conversationmessage USING btree (sent_to_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: property_property_favorited_property_id_8b3f7d6a; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX property_property_favorited_property_id_8b3f7d6a ON public.property_property_favorited USING btree (property_id);


--
-- Name: property_property_favorited_user_id_97ccb23a; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX property_property_favorited_user_id_97ccb23a ON public.property_property_favorited USING btree (user_id);


--
-- Name: property_property_landlord_id_2229dcf1; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX property_property_landlord_id_2229dcf1 ON public.property_property USING btree (landlord_id);


--
-- Name: property_reservation_created_by_id_7fe96819; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX property_reservation_created_by_id_7fe96819 ON public.property_reservation USING btree (created_by_id);


--
-- Name: property_reservation_property_id_6bda3f3f; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX property_reservation_property_id_6bda3f3f ON public.property_reservation USING btree (property_id);


--
-- Name: socialaccount_socialaccount_user_id_8146e70c; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX socialaccount_socialaccount_user_id_8146e70c ON public.socialaccount_socialaccount USING btree (user_id);


--
-- Name: socialaccount_socialtoken_account_id_951f210e; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX socialaccount_socialtoken_account_id_951f210e ON public.socialaccount_socialtoken USING btree (account_id);


--
-- Name: socialaccount_socialtoken_app_id_636a42d7; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX socialaccount_socialtoken_app_id_636a42d7 ON public.socialaccount_socialtoken USING btree (app_id);


--
-- Name: unique_primary_email; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE UNIQUE INDEX unique_primary_email ON public.account_emailaddress USING btree (user_id, "primary") WHERE "primary";


--
-- Name: unique_verified_email; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE UNIQUE INDEX unique_verified_email ON public.account_emailaddress USING btree (email) WHERE verified;


--
-- Name: useraccount_user_email_ad0e8321_like; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX useraccount_user_email_ad0e8321_like ON public.useraccount_user USING btree (email varchar_pattern_ops);


--
-- Name: useraccount_user_groups_group_id_9d49cea4; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX useraccount_user_groups_group_id_9d49cea4 ON public.useraccount_user_groups USING btree (group_id);


--
-- Name: useraccount_user_groups_user_id_fcea8d7d; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX useraccount_user_groups_user_id_fcea8d7d ON public.useraccount_user_groups USING btree (user_id);


--
-- Name: useraccount_user_user_permissions_permission_id_e65de47b; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX useraccount_user_user_permissions_permission_id_e65de47b ON public.useraccount_user_user_permissions USING btree (permission_id);


--
-- Name: useraccount_user_user_permissions_user_id_8fe888bb; Type: INDEX; Schema: public; Owner: postgresuser
--

CREATE INDEX useraccount_user_user_permissions_user_id_8fe888bb ON public.useraccount_user_user_permissions USING btree (user_id);


--
-- Name: account_emailaddress account_emailaddress_user_id_2c513194_fk_useraccount_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_2c513194_fk_useraccount_user_id FOREIGN KEY (user_id) REFERENCES public.useraccount_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_emailconfirmation account_emailconfirm_email_address_id_5b7f8c58_fk_account_e; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirm_email_address_id_5b7f8c58_fk_account_e FOREIGN KEY (email_address_id) REFERENCES public.account_emailaddress(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_useraccount_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_useraccount_user_id FOREIGN KEY (user_id) REFERENCES public.useraccount_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chat_conversation_users chat_conversation_us_conversation_id_4c0fbe59_fk_chat_conv; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.chat_conversation_users
    ADD CONSTRAINT chat_conversation_us_conversation_id_4c0fbe59_fk_chat_conv FOREIGN KEY (conversation_id) REFERENCES public.chat_conversation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chat_conversation_users chat_conversation_users_user_id_37f0921c_fk_useraccount_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.chat_conversation_users
    ADD CONSTRAINT chat_conversation_users_user_id_37f0921c_fk_useraccount_user_id FOREIGN KEY (user_id) REFERENCES public.useraccount_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chat_conversationmessage chat_conversationmes_conversation_id_cf6c6293_fk_chat_conv; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.chat_conversationmessage
    ADD CONSTRAINT chat_conversationmes_conversation_id_cf6c6293_fk_chat_conv FOREIGN KEY (conversation_id) REFERENCES public.chat_conversation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chat_conversationmessage chat_conversationmes_created_by_id_312d8431_fk_useraccou; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.chat_conversationmessage
    ADD CONSTRAINT chat_conversationmes_created_by_id_312d8431_fk_useraccou FOREIGN KEY (created_by_id) REFERENCES public.useraccount_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chat_conversationmessage chat_conversationmes_sent_to_id_6a38f604_fk_useraccou; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.chat_conversationmessage
    ADD CONSTRAINT chat_conversationmes_sent_to_id_6a38f604_fk_useraccou FOREIGN KEY (sent_to_id) REFERENCES public.useraccount_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_useraccount_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_useraccount_user_id FOREIGN KEY (user_id) REFERENCES public.useraccount_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: property_property_favorited property_property_fa_property_id_8b3f7d6a_fk_property_; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.property_property_favorited
    ADD CONSTRAINT property_property_fa_property_id_8b3f7d6a_fk_property_ FOREIGN KEY (property_id) REFERENCES public.property_property(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: property_property_favorited property_property_fa_user_id_97ccb23a_fk_useraccou; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.property_property_favorited
    ADD CONSTRAINT property_property_fa_user_id_97ccb23a_fk_useraccou FOREIGN KEY (user_id) REFERENCES public.useraccount_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: property_property property_property_landlord_id_2229dcf1_fk_useraccount_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.property_property
    ADD CONSTRAINT property_property_landlord_id_2229dcf1_fk_useraccount_user_id FOREIGN KEY (landlord_id) REFERENCES public.useraccount_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: property_reservation property_reservation_created_by_id_7fe96819_fk_useraccou; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.property_reservation
    ADD CONSTRAINT property_reservation_created_by_id_7fe96819_fk_useraccou FOREIGN KEY (created_by_id) REFERENCES public.useraccount_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: property_reservation property_reservation_property_id_6bda3f3f_fk_property_; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.property_reservation
    ADD CONSTRAINT property_reservation_property_id_6bda3f3f_fk_property_ FOREIGN KEY (property_id) REFERENCES public.property_property(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialtoken socialaccount_social_account_id_951f210e_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_account_id_951f210e_fk_socialacc FOREIGN KEY (account_id) REFERENCES public.socialaccount_socialaccount(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialtoken socialaccount_social_app_id_636a42d7_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_app_id_636a42d7_fk_socialacc FOREIGN KEY (app_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialaccount socialaccount_social_user_id_8146e70c_fk_useraccou; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_social_user_id_8146e70c_fk_useraccou FOREIGN KEY (user_id) REFERENCES public.useraccount_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: useraccount_user_groups useraccount_user_groups_group_id_9d49cea4_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.useraccount_user_groups
    ADD CONSTRAINT useraccount_user_groups_group_id_9d49cea4_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: useraccount_user_groups useraccount_user_groups_user_id_fcea8d7d_fk_useraccount_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.useraccount_user_groups
    ADD CONSTRAINT useraccount_user_groups_user_id_fcea8d7d_fk_useraccount_user_id FOREIGN KEY (user_id) REFERENCES public.useraccount_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: useraccount_user_user_permissions useraccount_user_use_permission_id_e65de47b_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.useraccount_user_user_permissions
    ADD CONSTRAINT useraccount_user_use_permission_id_e65de47b_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: useraccount_user_user_permissions useraccount_user_use_user_id_8fe888bb_fk_useraccou; Type: FK CONSTRAINT; Schema: public; Owner: postgresuser
--

ALTER TABLE ONLY public.useraccount_user_user_permissions
    ADD CONSTRAINT useraccount_user_use_user_id_8fe888bb_fk_useraccou FOREIGN KEY (user_id) REFERENCES public.useraccount_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict sTJl3Hi6DfgY8INlCdo82iGTgCljCpD5jTwFbjGkOHY4iWyKgeOE2FidZkxBi3f

